### ISSUE TITLE
Przysłać do mnie dostęp do systemu zarządzania projektem.

### ISSUE THREAD

**Issue by DariuszKonieczny** [dawidkwiatkowski/KFE#1]
Przysłać do mnie dostęp  do systemu zarządzania projektem.

**Comment by matektomek** [comment]
Już ma Pan dostęp do naszego systemu zarządzania projektem: https://www.gravitydev.com/project/53727/stories

Niefortunnie nazywa się inaczej niż repozytorium: Projekt Zespo?owy Kalambury
